bem/bem-xjst

lib/bemhtml/runtime/index.js
=> [4.x] Compiled bundle is broken after minification.

lib/bemhtml/runtime/context.js, test/runtime-test.js
=> fix generateId

lib/bemhtml/runtime/context.js
Can't find any usage of this field. Is it safe to remove?
cc @veged @indutny
=> Context: Remove unused BEM field

lib/compiler.js
=> compiler: Drop wrap method

package.json
=> package.json: Remove bundle command

lib/bemtree/index.js, test/bemtree/runtime-test.js
=> BEMTREE: return true as is

lib/bemhtml/index.js, test/bemhtml/runtime-test.js, test/bemhtml/tree-test.js
=> BEMHTML: mods field in BEMJSON should not be treated as elemMods

lib/bemhtml/index.js, test/bemhtml/runtime-test.js
Fixes: #111
P.S. Absolutely identical with https://github.com/bem/bem-xjst/pull/150
=> bemhtml: fix elemMods behaviour

CHANGELOG.md
I used https://github.com/rvagg/changelog-maker for commits list. Also I added notable changes for two lastest releases.
In future I'll try to write description to tags ([like in node.js](https://github.com/nodejs/node/commit/b21110f8a70b809b57b2c6639006674b6c6fe0b3)) and generate from it human readable changelog.
=> CHANGELOG.md added

lib/bemhtml/index.js, test/bemhtml/runtime-test.js
=> bemhtml: ignore empty string as modName and elemModName

common.blocks/demo/demo.js
=> Online demo: support sharing examples via URL params

lib/bemhtml/runtime/index.js, test/runtime-test.js
=> BEMHTML renderMix: skip mix item if falsy

CHANGELOG.md, README.md, README.ru.md, package.json
Docs for major release. Also `Readme.ru.md` updated.
=> Docs for v5.0.0

lib/bemhtml/entity.js, test/bemjson-tag-test.js, test/modes-tag-test.js
Immediate fix for https://github.com/bem/bem-xjst/issues/204
//cc @veged @tadatuta
=> BEMHTML: #204 Templates should be able to override tag from BEMJSON

lib/bemhtml/index.js, test/modes-mix-test.js
=> BEMHTML: fix rendering mixes for namesake elems

lib/bemxjst/index.js, test/bemcontext-position-test.js
#174 Fixed.
I want to cherry-pick the commit to 4.x and 5.x.
=> Fix for calc position

lib/bemxjst/tree.js, test/runtime-match-test.js
=> Pass context to wrap-based matchers and once

package.json
According to https://github.com/miripiruni/npm-pack-talk
=> Change files in package.json

lib/bemxjst/tree.js
=> Remove `elemMatch`

lib/bemxjst/index.js, test/bemcontext-mods-test.js
=> bemjxst: should keep `mods` in case of same block

.npmignore
=> Chore: Remove .npmignore

lib/bemxjst/index.js, test/bemjson-mods-test.js, test/modes-replace-test.js
https://nda.ya.ru/3RZ4pf
/cc @miripiruni
=> bemxjst: should not inherit `mods` from namesake parent block

lib/bemhtml/index.js, test/bemjson-attrs-test.js
=> BEMHTML: Should not render String or Array as attrs value

lib/bemhtml/index.js, test/bemjson-cls-test.js, test/modes-cls-test.js
=> BEMHTML: should trim and escape cls

docs/en/4-data.md, docs/ru/4-data.md
Результат не соответствовал входному BEMJSON.
=> Исправить ошибку финального HTML

test/runtime-escaping-test.js
=> Tests about escaping improved

.jshintrc, lib/bemhtml/runtime/index.js, test/runtime-test.js
=> BEMHTML: fix #303 bug with mix and render

lib/bemhtml/runtime/index.js, test/runtime-test.js
=> BEMHTML: Fix for #303 undefined nested mix

docs/ru/3-api.md
Правка не корректного примера в русской доке
=> Docs: example fixed 

docs/ru/3-api.md
=> Docs: example fixed

lib/bemhtml/index.js, lib/bemxjst/utils.js
=> BEMHMTL: split renderClose to renderAttrs and rest

lib/bemxjst/index.js, lib/bemxjst/utils.js, test/runtime-escaping-test.js
=> BEMXJST: work with empty string in html field

.travis.yml, README.md, README.ru.md, bench/package.json, lib/bemxjst/match.js, lib/bemxjst/tree.js, lib/bemxjst/utils.js, lib/compiler.js, package.json, test/bemcontext-generateid-test.js, test/bemcontext-identify-test.js, test/bemtree-test.js, test/fixtures.js, test/modes-def-test.js, test/modes-extend-test.js, test/modes-js-test.js, test/modes-mix-test.js, test/modes-replace-test.js, test/modes-tag-test.js, test/modes-wrap-test.js, test/runtime-bemcontext-test.js, test/templates-syntax-test.js
=> Code coverage

.travis.yml, bench/README.md, bench/apply-stand.js, bench/package.json, bench/prepare.sh, bench/run.js, bench/runner.js, bench/test.js, package.json
=> Bench: continuous benchmarking + more verbose results (For #85)

runtime-lint/index.js, runtime-lint/stand.js
Fix for #350 
Fix for #351
TODO
cc @a-x-
=> Runtime lint: check mix the same mods

.jshintrc, docs/en/5-templates-syntax.md, docs/ru/5-templates-syntax.md, lib/bemhtml/entity.js, lib/bemhtml/index.js, lib/bemxjst/index.js, lib/bemxjst/match.js, lib/bemxjst/tree.js, test/modes-addattrs-test.js, test/modes-addjs-test.js, test/modes-addmix-test.js, test/modes-attrs-test.js, test/modes-js-test.js, test/modes-mix-test.js
For #261 
Also fixed part of #174 
Also 64daa7fa2b7fc6ed48c347f9a1659b91730ce52c fixed issue #139
=> Semantic changes

.jshintrc, docs/en/5-templates-syntax.md, docs/ru/5-templates-syntax.md, lib/bemhtml/entity.js, lib/bemhtml/index.js, lib/bemxjst/index.js, lib/bemxjst/match.js, lib/bemxjst/tree.js, test/bemcontext-isfirst-test.js, test/bemcontext-islast-test.js, test/bemcontext-mods-test.js, test/bemcontext-position-test.js, test/modes-addelemmods-test.js, test/modes-addmods-test.js, test/modes-elemmods-test.js, test/modes-mods-test.js
=> Semantic: introduce mods(), addMods(), elemMods(), addElemMods()

docs/en/3-api.md, docs/ru/3-api.md, lib/bemhtml/index.js, lib/bemxjst/utils.js, test/bemhtml-test.js
Instead of https://github.com/bem/bem-xjst/pull/215
=> BEMHTML: Omit optional closing tags (fix for #360)

default_bemhtml.js, default_bemjson.js
Current example is awful. I try to change it with new possibilities:
— template body parameters instead of `this` and `this.ctx`
— arrow functions
— show `add*()` mode example
— show `match()` power
— add some comments about what it is
DEMO: https://goo.gl/6TbK7a
@tadatuta @zxqfox what you say?
=> Update default demo example (fix for #368)

README.md, README.ru.md
Fixes #390 
@tadatuta @zxqfox 
guys our README.md is ugly, outdated and non informative. I decide to make it fresh and more attractive.
* [Before](https://github.com/bem/bem-xjst/blob/master/README.md#bem-xjst) 
* [After](https://github.com/bem/bem-xjst/tree/new-readme__issue-390#bem-xjst)
I use [pug](https://www.npmjs.com/package/pug), [ejs](https://www.npmjs.com/package/ejs) readme as a reference.
I propose to examine the contents of the english version, after which I will translate it into russian.
=> Docs: readme updated (#390 fixed)

common.blocks/demo/demo.js
Fixes #320
Playground bug: ignores bemjson started not from 1th line #320
=> Online demo: trim BEMJSON input

lib/bemtree/index.js, lib/bemxjst/index.js, test/bemtree-test.js
=> BEMTREE: special unescaped html field from BEMJSON should render as is

common.blocks/demo/demo.js
=> Allow empty 'template' and use param 'bemhtml' as alias

lib/bemhtml/entity.js, lib/bemhtml/index.js, lib/bemtree/entity.js, lib/bemtree/index.js, lib/bemxjst/class-builder.js, lib/bemxjst/context.js, lib/bemxjst/entity.js, lib/bemxjst/error.js, lib/bemxjst/index.js, lib/bemxjst/match.js, lib/bemxjst/tree.js, lib/bemxjst/utils.js, lib/compiler.js, package.json, test/api-generate-test.js, test/bemjson-elemmods-test.js, test/bemjson-values-test.js, test/flush-test.js, test/templates-syntax-test.js
Fixes #404 
before: 97%
after: 99,6%
Before:
bemhtml-master.gz 10120B
After:
bemhtml-compressed.gz 9494B
*Total: –6,09% (–626B).*
Command:
`$ ./node_modules/.bin/uglifyjs ./lib/bemhtml/bundle.js | gzip > bemhtml-compressed.gz`
JFYI: `_search.client.bemhtml.js 29754B` 
After my optimization web4 bemhtml client bundle will decreased to 29166B :(
* * *
28% профита получат те, кто захочет сделать npm i bem-xjst и подключить бандл на клиент. (результаты и сокращений в коде и результаты запуска uglify в pre-publish).
6% профита получат те, кто встроят этот бандл (только результаты сокращения кода).
=> Optimize bundle size

lib/bemhtml/entity.js, lib/bemhtml/index.js, lib/bemtree/entity.js, lib/bemtree/index.js, lib/bemxjst/class-builder.js, lib/bemxjst/context.js, lib/bemxjst/entity.js, lib/bemxjst/index.js, lib/bemxjst/match.js, lib/bemxjst/tree.js, lib/bemxjst/utils.js, lib/compiler.js, package.json
Fixes #404 
–4,62% (–455B)
Before: 9853B
After: 9398B
=> Issue 404  bundle size v7.x

lib/bemxjst/tree.js, test/modes-match-test.js
=> TREE: Match must have an argument 

lib/bemxjst/tree.js, test/modes-appendcontent-test.js, test/modes-prependcontent-test.js
=> TREE: fixed append/prepend content with function body

lib/bemhtml/index.js, test/bemhtml-test.js
=> BEMHTML: unquotedAttrs should escape attributes

lib/bemhtml/api.js, lib/bemhtml/compiler.js, lib/bemhtml/runtime/class-builder.js, lib/bemhtml/runtime/context.js, lib/bemhtml/runtime/entity.js, lib/bemhtml/runtime/index.js, lib/bemhtml/runtime/match.js, lib/bemhtml/runtime/tree.js, lib/bemhtml/runtime/utils.js, package.json
=> Issue 404  bundle size in v4.x

lib/bemxjst/index.js, test/bemcontext-position-test.js
=> BEMXJST: applyCtx fixes

lib/bemhtml/index.js, lib/bemxjst/index.js, test/modes-attrs-test.js
=> BEMXJST: run() should revert depth

lib/bemhtml/index.js, test/bemjson-js-test.js
=> BEMHTML: fix render i-bem when mix elem with js (fix #441)

lib/bemxjst/index.js, test/init-test.js
=> BEMXJST: should exec new oninit functions on every compile (fix #356)

lib/compiler.js, test/api-generate-test.js
=> Generate should generate valid CommonJS module

runtime-lint/README.md, runtime-lint/index.js, runtime-lint/stand.js
=> Runtime lint: modifier values can’t be Array type (fix for #420)

lib/bemhtml/index.js
=> Remove ul and ol from list of optional tags, they are NOT optional

docs/en/3-api.md, docs/ru/3-api.md, lib/bemxjst/context.js, lib/bemxjst/index.js, package.json, test/bemcontext-custom-error-logger-test.js
=> BEMXJST: API for custom error logger (fix for #475)

lib/compiler.js, test/api-generate-test.js
Fixes #
require module issues: 
- when you require a module giving it the name different from original, module provided still has original name.
- actually no modules provided to buildBemXjst
_added miripiruni to my fork_
=> Compiler: several require fixes

lib/bemxjst/index.js, lib/bemxjst/tree.js, test/modes-wrap-test.js
=> bem-xjst: Wrap should save BEMContext

docs/en/3-api.md, docs/ru/3-api.md, lib/bemxjst/match.js, lib/compiler.js, package.json
Related: 
* https://github.com/enb/enb-source-map/pull/19
* https://github.com/enb/enb-bemxjst/pull/284
cc @sbmaxx
=> Previous source maps support

docs/en/5-templates-syntax.md, docs/ru/5-templates-syntax.md
very common mode syntax misspel
=> Fix appendContent mode docs

lib/compiler.js
=> Compiler: runtime lint path fixed (issue #502)

lib/compiler.js
=> Compiler: runtime lint path fixed

docs/en/4-data.md, docs/ru/4-data.md
Fixes #423 
Documentation about hidden feature: attrs hash templating.
cc @Yeti-or
=> Docs: attrs templating hidden feature

runtime-lint/index.js
Fixes #474 
Custom stringify function for runtime liner.
=> Runtime lint: custom stringify function

runtime-lint/index.js, runtime-lint/stand.js
Fixes #503
A brief introductory comment https://github.com/bem/bem-xjst/issues/503#issuecomment-379802971
=> Runtime lint: remove useless mods/elemMods checks

.gitignore
Fixes #
- Added `.idea` folder to `.gitignore` (created by JetBrains' IDEs)
- Added `coverage` folder to `.gitignore` (created while running `npm test`)
=> Added .idea and coverage folders to .gitignore

lib/bemhtml/index.js
Fixes #
- use Set to track visited class names
- use minimalistic polyfill where Set is not available
#538
=> BEMHTML: performance optimization in BEMHTML.prototype.renderMix

lib/bemhtml/index.js, lib/bemtree/index.js, test/templates-syntax-test.js
=> bem-xjst: export BEMXJSTError

.gitignore, bench/README.md, bench/run.js, bench/runner.js, bench/test.js, lib/bemhtml/index.js, lib/bemxjst/index.js, lib/bemxjst/match.js, lib/bemxjst/utils.js, test/bemcontext-custom-error-logger-test.js
- benchmarking code and documentation are updated
- `utils.isSimple` is optimized
- `Set` is removed because more thorough benchmarks showed no performance improvement in Node.js
Compare 8.9.4 (rev1) with latest version in PR (rev2):
```
Percentile:  0.5
{ rev1: 4.963768,
rev2: 4.771325,
'diff abs': 0.19244299999999992,
'diff percent': 3.8769539591697266 }
Percentile:  0.9
{ rev1: 7.333798,
rev2: 7.017333,
'diff abs': 0.316465,
'diff percent': 4.315158394054485 }
Percentile:  0.95
{ rev1: 8.290766,
rev2: 7.943027,
'diff abs': 0.3477389999999998,
'diff percent': 4.19429278307939 }
```
=> Performance optimization

.gitignore, bench/README.md, bench/package.json, bench/run.js, bench/runner.js, bench/test.js, lib/bemhtml/index.js, lib/bemxjst/index.js
- benchmarking code and documentation are updated
- `utils.isSimple` is optimized
- `Set` is removed because more thorough benchmarks showed no performance improvement in Node.js
Compare 7.8.0 (rev1) with latest version in PR (rev2):
```
Percentile:  0.5
{ rev1: 6.182898,
rev2: 5.803587,
'diff abs': 0.3793109999999995,
'diff percent': 6.134841622811815 }
Percentile:  0.9
{ rev1: 8.711171,
rev2: 8.236423,
'diff abs': 0.47474799999999995,
'diff percent': 5.449875797410019 }
Percentile:  0.95
{ rev1: 9.772233,
rev2: 9.349094,
'diff abs': 0.4231390000000008,
'diff percent': 4.330013416585555 }
```
=> Performance optimization 7.x

lib/bemxjst/utils.js, test/bemcontext-attrescape-test.js, test/bemjson-cls-test.js, test/modes-cls-test.js
Add `<` and `>` escaping in `attrEscape` (SERP-67383)
=> Escape attrs from xml tags
