- lib/bemhtml/runtime/index.js
- test/runtime-test.js
Closes #124
WARNING! Looks like bem-xjst 1.x results with `some-attr=[object Object]` for `attrs()({ 'some-attr': { block: 'b1' } })` (see expected section of #124) which I think is also wrong.
cc @indutny @veged @blond
> Support attrs values as an object

- bench/package.json
- lib/bemhtml/runtime/tree.js
- test/runtime-test.js
Related to #49 
tadatuta@tadatuta-osx:~/Sites/bem-xjst-new/bench$ node run.js --compare
render:basic:next x 582,915 ops/sec ±1.07% (86 runs sampled)
render:basic:prev x 627,541 ops/sec ±0.98% (83 runs sampled)
render:islands:next x 984 ops/sec ±1.37% (85 runs sampled)
render:islands:prev x 963 ops/sec ±1.50% (84 runs sampled)
render:showcase:next x 1,912 ops/sec ±1.23% (86 runs sampled)
render:showcase:prev x 1,853 ops/sec ±1.09% (86 runs sampled)
tadatuta@tadatuta-osx:~/Sites/bem-xjst-new/bench$ node run.js --compare
render:basic:next x 645,760 ops/sec ±1.58% (86 runs sampled)
render:basic:prev x 658,075 ops/sec ±1.61% (85 runs sampled)
render:islands:next x 922 ops/sec ±1.02% (85 runs sampled)
render:islands:prev x 917 ops/sec ±1.37% (83 runs sampled)
render:showcase:next x 1,786 …
> Throw error if args passed to shortcut predicates

- lib/bemxjst/match.js
- test/bemhtml/tree-test.js
Always execute matches in the same order as they came in the input file.
Fix: #146
> bemxjst: fix order of execution of `match`es

- lib/bemxjst/class-builder.js
- test/bemhtml/runtime-test.js
> class-builder: `elem === ''` means no elem

- lib/bemhtml/runtime/index.js
- test/runtime-test.js
> BEMHTML: should properly render attr values

- lib/bemhtml/index.js
- test/bemjson-mix-test.js
Related: https://github.com/bem/bem-core/pull/805
+15 test cases
–1 bug
Because block class must have for mix block with mods to block elem.
Example:
```js
({
block: 'b',
content: {
elem: 'e',
mix: [
{ block: 'b', mods: { m1: 'v1' } },
{ block: 'b', mods: { m2: 'v2' } }
]
}
});
```
4.3.4 result:
```html
<div class="b"><div class="b__e b b_m1_v1 b b_m2_v2"></div></div>
```
[demo](http://bem.github.io/bem-xjst/?bemhtml=&bemjson=(%7B%0A%20%20%20%20block%3A%20%27b%27%2C%0A%20%20%20%20content%3A%20%7B%0A%20%20%20%20%20%20%20%20elem%3A%20%27e%27%2C%0A%20%20%20%20%20%20%20%20mix%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7B%20block%3A%20%27b%27%2C%20mods%3A%20%7B%20m1%3A%20%27v1%27%20%7D%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%7B%20block%3A%20%27b%27%2C%20mods%3A%20%7B%20m2%3A%20%27v …
> Improved mix behaviour

- lib/bemxjst/match.js
- test/runtime-match-test.js
Fixes #171 
Was not done:
```js
block('*').content()((_, ctx) => [ctx.text, applyNext()]);
```
because it's a sugar for:
```js
block('*').content()({ctx} => [ctx.text, applyNext()]);
```
I'm not sure what's sweeter.
> Pass BEMContext instance as argument to template body

- .jshintrc
- lib/bemxjst/error.js
- lib/bemxjst/index.js
- lib/compiler.js
- test/templates-syntax-test.js
```bash
miripiruni$ cat noblock.js
var bemxjst = require('./');
var bemhtml = bemxjst.bemhtml;
var templates = bemhtml.compile(function() {
elemMod('em', 'ev')
.mod('m', 'v')
.elem('e')
.attrs()(function() {
return { id: 'test' };
});
});
```
```bash
miripiruni$ node noblock.js
evalmachine.<anonymous>:804
throw new Error('block("...") not found in one of the templates');
^
Error: block("...") not found in one of the templates
at BEMHTML.groupEntities (evalmachine.<anonymous>:804:13)
at BEMHTML.compile (evalmachine.<anonymous>:750:18)
at evalmachine.<anonymous>:1899:5
at Compiler.compile (/Users/miripiruni/Documents/www/bem-xjst-cls/lib/compiler.js:65:3)
at Object.<anonymous> (/Users/miripiruni/Documents/www/bem-xjst-cls/noblock.js:3:25)
…
```
```bash
miripiruni$ node noblock.js …
```
> Improved error msg about no block subpredicate (print out template)

- .jshintrc
- lib/bemxjst/match.js
- lib/compiler.js
- package.json
- test/api-compile-test.js
- test/modes-elemmod-test.js
Fix for #259 
So, the checks have failed [because of Node v0.1 and Node v0.12](https://travis-ci.org/bem/bem-xjst/builds/131134175). 
WIP: I would like to disable ES6 tests for old Node.js. 
cc @zxqfox
> BEMXJST: generate() should support arrow functions

- lib/bemhtml/entity.js
- lib/bemhtml/index.js
- lib/bemtree/entity.js
- lib/bemxjst/entity.js
- lib/bemxjst/index.js
- lib/bemxjst/match.js
- test/modes-attrs-test.js
- test/modes-js-test.js
- test/modes-mix-test.js
- test/runtime-apply-test.js
Fix for #236 
Benchmarks test results within the error: (+/– 1% in different bundles).
> `apply(modeName)` must return values from `this.ctx` if no other templates

- docs/en/5-templates-syntax.md
- docs/ru/5-templates-syntax.md
- lib/bemxjst/match.js
- lib/bemxjst/tree.js
- test/modes-elemmod-test.js
- test/modes-mod-test.js
Fix #220 
Benchmarks result within the error.
> Match: check mods/elemMods subpredicates after it’s converting to strings

- lib/bemxjst/index.js
- test/runtime-escaping-test.js
> BEMHTML: should properly render unescaped html field if `tag:false` present

- lib/bemhtml/runtime/index.js
- test/runtime-test.js
See #298
Original task: https://nda.ya.ru/3RiZp2
> Try/catch for 4.x

- lib/bemxjst/utils.js
See #327 
Bench results:
```bash
https://github.com/component/escape-html version:
no special characters    x 22,456,447 ops/sec ±2.61% (192 runs sampled)
single special character x  7,241,378 ops/sec ±1.32% (191 runs sampled)
many special characters  x  3,542,471 ops/sec ±0.87% (192 runs sampled)
old bem-xjst 7.0.3 utils.xmlEscape version:
no special characters    x  3,621,962 ops/sec ±2.34% (184 runs sampled)
single special character x  2,796,355 ops/sec ±0.92% (192 runs sampled)
many special characters  x  1,545,772 ops/sec ±0.86% (194 runs sampled)
```
I decided to update `utils.*Escape` functions.
> Utils: faster escaping functions (see issue #327)

- .jshintrc
- docs/en/5-templates-syntax.md
- docs/ru/5-templates-syntax.md
- lib/bemxjst/index.js
- lib/bemxjst/match.js
- lib/bemxjst/tree.js
- test/modes-appendcontent-test.js
- test/modes-prependcontent-test.js
Main goal (IMHO): more verbose `appendContent()` rather than `return [ applyNext(), '...' ];`
Some real life code: 
[1](https://nda.ya.ru/3RttkR), [2](https://nda.ya.ru/3Rttmt), [3](https://nda.ya.ru/3Rttnu), [4](https://nda.ya.ru/3RttoN), [5](https://nda.ya.ru/3RttoW), [6](https://nda.ya.ru/3Rttoi), [7](https://nda.ya.ru/3Rttov), [8](https://nda.ya.ru/3Rttox), [9](https://nda.ya.ru/3Rttp3), [10](https://nda.ya.ru/3Rttp5), [11](https://nda.ya.ru/3RttpT), [12](https://nda.ya.ru/3RttpV), [13](https://nda.ya.ru/3RttpX) and etc.
In general, `appendContent()` is shortcut to:
```js
content()(function() {
return [apply('content'), 'Append Me' ];
});
```
`prependContent()` is shortcut to:
```js
content()(function() {
return [ 'Prepend Me' , apply('content') ];
});
```
> New modes: appendContent and prependContent

- lib/bemhtml/entity.js
BEMHTML: `Entity.mod` is useless.
See https://github.com/bem/bem-xjst/commit/6280278b04179f89881f62bf6902b498e58d78b8#diff-bad194964bfd200986dd4bcaf15c2303R20
> TRIVIAL: mod removed as useless

- runtime-lint/index.js
- runtime-lint/stand.js
> Runtime lint: Warning about class or data-bem in `attrs`

- docs/en/5-templates-syntax.md
- docs/ru/5-templates-syntax.md
- lib/bemxjst/match.js
- lib/bemxjst/tree.js
- test/modes-elemmod-test.js
- test/modes-mod-test.js
Fixed #274 
Am I do it right?
//cc @veged @zxqfox
> Support `mod(m)` and `elemMod(em)` without second argument

- docs/en/5-templates-syntax.md
- docs/ru/5-templates-syntax.md
- lib/bemxjst/match.js
- lib/bemxjst/tree.js
- test/modes-extend-test.js
> BEMXJST: extend() mode fix #180

- docs/en/6-templates-context.md
- docs/ru/6-templates-context.md
@tadatuta @zxqfox давайте согласуем сначала русскоязычную версию, а затем я добавлю перевод на английский, OK? Сейчас эта информация совсем не раскрыта в доке. Я решил срочно дополнить.
> Docs: write about template arguments and arrow function (fix for #367)

- lib/bemxjst/tree.js
- test/modes-extend-test.js
> Provide arguments for extend() mode

- lib/bemxjst/tree.js
- test/bemcontext-position-test.js
> BEMHTML: fix position with replace()

- .enb/techs/bemxjst.js
- .enb/techs/i18n.js
Добавил в сборку объект  BEM.I18N которая является функцией и возвращает второй аргумент.
Теперь можно вставлять в песочницу код, который с BEM.I18N('form', 'form-important-args')
> issue #231 

- lib/bemxjst/tree.js
- package.json
- minus one dependency: [minimalistic-assert](https://github.com/calvinmetcalf/minimalistic-assert)
- minus 343 bytes (~0,7%) in every bundle
> Deps: throw away minimalistic-assert dependency

- index.js
- lib/bemxjst/index.js
- lib/compiler.js
- package.json
- runtime-lint/index.js
Fixes #407 
- use required bem-xjst instead of bundled
- All public API not changed
```js
$ cat test.js
var bemhtml = require('./').bemhtml;
var libs = {
jscs: require('jscs'),
chai: require('chai')
};
var templates = function templates() {
block('a').content()(function() {
console.log(this.require('chai').version);
console.log(this.chai.version);
return applyNext();
});
};
var htmlTemplates = bemhtml.compile(templates);
htmlTemplates.BEMContext.prototype.require = function require(libName) {
return libs[libName];
};
htmlTemplates.BEMContext.prototype.chai = require('chai');
var bemjson = { block: 'a', content: 'First' };
console.log(htmlTemplates.apply(bemjson));
htmlTemplates.compile(function() {
block('a').mix()('mixed');
});
console.log(htmlTemplates.apply(bemjson)); …
```
> Use bem-xjst in Node.js without bundling via browserify (#407 fixed)

- lib/compiler.js
Because of enb-bemxjst use mockFs.
https://github.com/enb/enb-bemxjst/commit/0898f103dc73d873e55bd29558060a9e3717519b#diff-8e61276023edef77cdb47a206a441d33L308
And because of we can require once at start.
> Compiler .generate(): do not require in runtime

- lib/bemxjst/index.js
- test/init-test.js
`oninit` should have global context at least for backward compatibility.
> BEMXJST: Revert exportApply optimization

- lib/bemxjst/index.js
It was removed in https://github.com/bem/bem-xjst/commit/4ed06f1b84951081870702124e221806b4ee7614#diff-afb54847cb75c3ad58adbcd400fa4c46L120 and results in that [__bem_xjst_libs__](https://github.com/enb/enb-bemxjst/search?utf8=✓&q=__bem_xjst_libs__) is now `undefined`.
Caught in `bem-core` tmpl specs.
> Rollback function reuse in recompileInput

- docs/en/3-api.md
- docs/ru/3-api.md
- lib/compiler.js
- package.json
- test/api-generate-test.js
> Compiler.generate: support YModules, CommonJS and global dependencies

- lib/bemhtml/runtime/match.js
This possibly fixes memory leaks in Match instances in #433
> Fixed this.restoreDepth call possibly

- docs/en/3-api.md
- docs/ru/3-api.md
Fixes #397 
I found that if I change exportName option to something not `bemhtml` or `bemtree` then compiler falls with error.
I think there is something unintelligible. We have two options: `engine` and `exportName`. In the beginning, I thought `exportName` determines name of variable that contains bundle and `engine` determines which engine (BEMHTML/BEMTREE) need to export.
But it works not so: `exportName` and `engine` can be only `BEMHTML` or `BEMTREE`.
May I change it like I do it it in PR?
> Proposal: fix exportName option

- common.blocks/demo/demo.deps.js
- common.blocks/demo/demo.js
- common.blocks/engine-selector/engine-selector.js
- common.blocks/version-selector/version-selector.bemhtml.js
- common.blocks/version-selector/version-selector.js
- desktop.bundles/index/index.bemjson.js
Fixes #389 
- drops load the default `xbrowser.bemhtml.js` bundle during the page load: now it loads dynamically corresponding to value from engine select (the last version is default, so nothing's changed here)
- `version` and `engine` into URL, saved on every select change
I've encountered a problem. You can face it if change version below 8.4.0, pick BEMTREE and reload the page: `this._engine is not define` instead of rendered bemjson from the bemtree template.
**Why this happens**
The bundle actually doesn't have `BEMTREE` as a global object, so when you change the version within select in runtime everything is okay, because you actually use `BEMTREE` **from the old bunlde**. In current production the first bundle (version 8.5.2) loads every time, so you can't see the effect.
I'm not …
> feat (Demo): engine and version into URL

- bin/bem-xjst
- docs/en/3-api.md
- docs/ru/3-api.md
- examples/source-maps/demo1/b1.bemhtml.js
- examples/source-maps/demo1/demo1.html
- examples/source-maps/demo1/demo1.js
- examples/source-maps/demo2/demo2.html
- examples/source-maps/demo2/demo2.js
- examples/source-maps/demo2/tmpls-with-sourcemap.bemhtml.js
- examples/source-maps/demo3/b3.bemhtml.js
- examples/source-maps/demo3/demo3.html
- examples/source-maps/demo3/demo3.js
- lib/compiler.js
- package.json
Fixes #108
Instead of #160 
Related: https://github.com/enb/enb-source-map/pull/18
> Source map support (issue #108)

- lib/bemhtml/index.js
- test/bemjson-mix-test.js
Fix #241 
Instead of https://github.com/bem/bem-xjst/pull/280
> BEMHTML: support nested mixes

- docs/en/3-api.md
- docs/ru/3-api.md
- lib/bemxjst/class-builder.js
- test/custom-naming-test.js
Fixes #469 
Now `naming` option can be:
1) {String}.
2) {Object}: `{name: '…', val: '_' }`.
Default value of naming wasn’t changed. Backward capability is supported.
cc @zxqfox
> Class builder: mod val delimeter

- lib/compiler.js
Fixes 
BEMHTML generate bug - do not exports to commonJS
> BEMHTML: fix compiler for module.exports

- lib/bemhtml/index.js
- test/bemjson-bem-test.js
- test/modes-bem-test.js
>  BEMHTML: cls and bem:false fix

- lib/compiler.js
- test/api-generate-test.js
Gets dot-delimited deps from global scope in object notation
> Global dot delimited deps

- docs/en/3-api.md
- docs/ru/3-api.md
- lib/bemhtml/index.js
- test/bemhtml-test.js
- test/templates-syntax-test.js
Fixes #504
New option `singleQuotesForDataAttrs`.
By default data-attributes values will be marked with double quotes. For BEMJSON:
```js
{
block: 'b',
attrs: {
id: 'without-changes',
'data-test': '{"reqid":"42"}'
}
}
```
*Result of templating:*
```html
<div class="b" id="without-changes" data-test="{&quot;reqid&quot;:&quot;42&quot;}"></div>
```
All double quotes inside `data-test` value was escaped. If you want to avoid such behaviour you can use `singleQuotesForDataAttrs` option.
```js
var bemxjst = require('bem-xjst');
var templates = bemxjst.bemhtml.compile(() => {
// In this example we will add no templates.
// Default behaviour is used for HTML rendering.
}, {
// use single quotes for data-* attributes
singleQuotesForDataAttrs: true
});
var bemjson = { block: 'b', attrs: {
id: …
```
> Single quotes in js attrs

- lib/compiler.js
- test/api-generate-test.js
Backward capability was ruined after v8.6.8
https://github.com/bem/bem-xjst/commit/b20bb52bfd9d73f81e13f7164c21104b7f4fdc64#diff-ee97c5091b89979aace94674818996baL32
For fixing default value of export name we rollback the changes.
See issue #516
> Compiler: default exportName returned to uppercase

- package.json
```
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
```
> package.json: prepublish -> prepare

- package.json
Бот гитхаба ругается:
`
bem-xjst@8.9.6 requires atob@2.0.3 via enb-source-map@1.12.0
`
> package.json: Update enb-source-map
